### ISSUE TITLE
Backward error

### ISSUE THREAD

**Issue by milesigel** [Asthestarsfalll/Symbolic-Music-Genre-Transfer-with-CycleGAN-for-pytorch#2]
Any idea how to solve this or if you had the same issue?

RuntimeError                              Traceback (most recent call last)
<ipython-input-42-b3abb9101fab> in <module>
    132         D_loss = d_loss + gamma * d_all_loss
    133 
--> 134         d_A_loss.backward(retain_graph=True)
    135         d_B_loss.backward(retain_graph=True)
    136 

/software/python3/3.9.5/lib/python3.9/site-packages/torch/tensor.py in backward(self, gradient, retain_graph, create_graph, inputs)
    243                 create_graph=create_graph,
    244                 inputs=inputs)
--> 245         torch.autograd.backward(self, gradient, retain_graph, create_graph, inputs=inputs)
    246 
    247     def register_hook(self, hook):

/software/python3/3.9.5/lib/python3.9/site-packages/torch/autograd/__init__.py in backward(tensors, grad_tensors, retain_graph, create_graph, grad_variables, inputs)
    143         retain_graph = create_graph
    144 
--> 145     Variable._execution_engine.run_backward(
    146         tensors, grad_tensors_, retain_graph, create_graph, inputs,
    147         allow_unreachable=True, accumulate_grad=True)  # allow_unreachable flag

RuntimeError: one of the variables needed for gradient computation has been modified by an inplace operation: [torch.cuda.FloatTensor [1, 64, 7, 7]] is at version 55; expected version 22 instead. Hint: the backtrace further above shows the operation that failed to compute its gradient. The variable in question was changed in there or anywhere later. Good luck!

**Comment by Asthestarsfalll** [comment]
![image](https://user-images.githubusercontent.com/72954905/126099225-29ac26aa-dbdb-4edb-af26-8628f3aea4fd.png)
adding `retain_graph=True` in line 138 may solve this problem

**Comment by Asthestarsfalll** [comment]
i am trying to sovle this problem

**Comment by Asthestarsfalll** [comment]
![image](https://user-images.githubusercontent.com/72954905/126149299-773e81a6-0a18-4946-ba22-a9849b71ffec.png)
modify the code like this , and I think the version of torch that you use is too high, try to use the version 1.4

**Comment by milesigel** [comment]
I figured out how to amend this error and have working .pth files. For others who might have this problem, I just made a separate conda environment.
