### ISSUE TITLE
Great work! But I have encountered some problems about the dataset

### ISSUE THREAD

**Issue by ShawnPi233** [Asthestarsfalll/Symbolic-Music-Genre-Transfer-with-CycleGAN-for-pytorch#3]
As is mentioned in the title, I can hardly get access to the full of dataset which is offered in the project. Because I find that when I extract the .zip file, **I only get the `CP_C`、`CP_P` and `JCP_mixed` file folder** without other data relevant to jazz piano. 
Hopefully you would pay attention to my problem, thanks ! !

**Comment by Asthestarsfalll** [comment]
Hi, @ShawnPi233 
It seems some errors occur when extracting. I encountered the same problems on Windows operating system. But the dataset is able to be completely extracted on Linux. Maybe you can try other software to extract.

**Comment by ShawnPi233** [comment]
> Hi, @ShawnPi233 It seems some errors occur when extracting. I encountered the same problems on Windows operating system. But the dataset is able to be completely extracted on Linux. Maybe you can try other software to extract.

Thanks! When I use the 7-Zip File Manager to extract the dataset, it works well
