### ISSUE TITLE
关于retain_graph=True显存爆炸的问题

### ISSUE THREAD

**Issue by xmutly** [Asthestarsfalll/Symbolic-Music-Genre-Transfer-with-CycleGAN-for-pytorch#4]
哈喽哈喽，我把您的code用在自己的数据集上，但是这六个loss都有retain_graph=True导致显存爆炸，但是去掉retain_graph的话，又会导致梯度反传失败，请问您如何解决的呢？

**Comment by Asthestarsfalll** [comment]
> 哈喽哈喽，我把您的code用在自己的数据集上，但是这六个loss都有retain_graph=True导致显存爆炸，但是去掉retain_graph的话，又会导致梯度反传失败，请问您如何解决的呢？

由于有多次反向传播，因此retain graph不可以去掉，可以调小batch size试试

**Comment by xmutly** [comment]
> > 哈喽哈喽，我把您的code用在自己的数据集上，但是这六个loss都有retain_graph=True导致显存爆炸，但是去掉retain_graph的话，又会导致梯度反传失败，请问您如何解决的呢？
> 
> 由于有多次反向传播，因此retain graph不可以去掉，可以调小batch size试试

目前我的BS=1了，我是直接用时频图来做的，时频图大小是64x64，随着step的累积，仍然会爆炸 : (

**Comment by Asthestarsfalll** [comment]
可能是哪里显存泄漏了，需要自行debug
